name: CI
on:
  push: null
permissions:
  contents: read
jobs:
  container-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false
    - name: Extract version of Go to use
      run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile)" >> $GITHUB_ENV
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
      with:
        go-version: ${{ env.GOVERSION }}
    - uses: ko-build/setup-ko@d982fec422852203cfb2053a8ec6ad302280d04d
    - name: container
      run: 'make ko-local

        docker run --rm $(cat rekorImagerefs) version

        docker run --rm $(cat cliImagerefs) version

        docker run --rm $(cat indexImagerefs) --version

        '
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false
    - name: Extract version of Go to use
      run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile)" >> $GITHUB_ENV
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
      with:
        go-version: ${{ env.GOVERSION }}
    - name: Build
      run: make -C $GITHUB_WORKSPACE all
    - name: Fuzz-Build
      run: make -C $GITHUB_WORKSPACE fuzz
    - name: Test
      run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Upload Coverage Report
      uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574
      with:
        flags: unittests
    - name: Ensure no files were modified as a result of the build
      run: git update-index --refresh && git diff-index --quiet HEAD -- || git diff --exit-code
      id: _bre_build
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@40e9946c182a64b3db1bf51be0dcb915f7802aa9
    - name: download minisign
      run: 'brew install minisign

        '
    - name: Extract version of Go to use
      run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile)" >> $GITHUB_ENV
    - name: install gocovmerge
      run: make gocovmerge
    - name: CLI mysql index
      run: ./tests/e2e-test.sh
      env:
        INDEX_BACKEND: mysql
    - name: CLI redis index
      run: ./tests/e2e-test.sh
      env:
        INDEX_BACKEND: redis
    - name: Refactor-e2e mysql index
      run: ./e2e-test.sh
      env:
        INDEX_BACKEND: mysql
    - name: Refactor-e2e redis index
      run: ./e2e-test.sh
      env:
        INDEX_BACKEND: redis
    - name: Upload logs if they exist
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
      if: failure()
      with:
        name: E2E Docker Compose logs
        path: /tmp/docker-compose.log
    - name: Upload Coverage Report
      uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574
      with:
        files: /tmp/rekor-merged.cov,/tmp/pkg-rekor-merged.cov
        flags: e2etests
    - name: Set up Homebrew
      id: backfill_set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@40e9946c182a64b3db1bf51be0dcb915f7802aa9
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: download minisign
      run: 'brew install minisign

        '
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Extract version of Go to use
      run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile)" >> $GITHUB_ENV
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Install backfill test dependencies
      run: 'go install ./cmd/rekor-cli

        sudo add-apt-repository ppa:savoury1/minisign && sudo apt-get update && sudo apt-get install minisign

        sudo apt install redis-tools default-mysql-client -y

        '
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Backfill test redis
      run: ./tests/backfill-test.sh
      env:
        INDEX_BACKEND: redis
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Backfill test mysql
      run: ./tests/backfill-test.sh
      env:
        INDEX_BACKEND: mysql
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Cleanup index test
      run: ./tests/cleanup-index-test.sh
      env:
        INDEX_BACKEND: redis
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Copy index test
      run: ./tests/copy-index-test.sh
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Upload logs if they exist
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
      if: (!cancelled() && steps._bre_build.conclusion == 'success') && (failure())
      with:
        name: E2E Docker Compose logs
        path: /tmp/docker-compose.log
    - name: Set up Homebrew
      id: sharding_e2e_set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@40e9946c182a64b3db1bf51be0dcb915f7802aa9
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: download minisign
      run: 'brew install minisign

        '
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Docker Build
      run: docker compose build
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Extract version of Go to use
      run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile)" >> $GITHUB_ENV
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Sharding Test
      run: ./tests/sharding-e2e-test.sh
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Upload logs if they exist
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
      if: (!cancelled() && steps._bre_build.conclusion == 'success') && (failure())
      with:
        name: Sharding E2E Docker Compose logs
        path: /tmp/docker-compose.log
    - name: Docker Build
      run: docker compose build
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Extract version of Go to use
      run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile)" >> $GITHUB_ENV
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Test for Attestation begin returned that was previously persisted in tlog
      run: ./tests/issue-872-e2e-test.sh
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Upload logs if they exist
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
      if: (!cancelled() && steps._bre_build.conclusion == 'success') && (failure())
      with:
        name: Docker Compose logs
        path: /tmp/*docker-compose.log
    - name: Docker Build
      run: docker compose build
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Extract version of Go to use
      run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile)" >> $GITHUB_ENV
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Test for supported client algorithms
      run: ./tests/client-algos-e2e-test.sh
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Upload logs if they exist
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
      if: (!cancelled() && steps._bre_build.conclusion == 'success') && (failure())
      with:
        name: Docker Compose logs
        path: /tmp/*docker-compose.log
    - name: Create git branch
      run: git switch -c harness-test-branch
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Extract version of Go to use
      run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile)" >> $GITHUB_ENV
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
      with:
        go-version: ${{ env.GOVERSION }}
        check-latest: true
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Run test harness
      run: ./tests/rekor-harness.sh
      if: '!cancelled() && steps._bre_build.conclusion == ''success'''
    - name: Upload logs if they exist
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
      if: (!cancelled() && steps._bre_build.conclusion == 'success') && (failure())
      with:
        name: E2E Docker Compose logs
        path: /tmp/docker-compose.log
